// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using go_han.Data;

#nullable disable

namespace go_han.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115082828_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("go_han.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DivisionName = "Frontend Dev"
                        },
                        new
                        {
                            Id = 2,
                            DivisionName = "Backend Dev"
                        });
                });

            modelBuilder.Entity("go_han.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoLeadId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoLeadId");

                    b.HasIndex("LeadId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoLeadId = 2,
                            Description = "Description A",
                            EndDate = new DateTime(2026, 1, 22, 15, 28, 28, 23, DateTimeKind.Local).AddTicks(4990),
                            LeadId = 1,
                            ProjectName = "Project A",
                            StartDate = new DateTime(2026, 1, 15, 15, 28, 28, 23, DateTimeKind.Local).AddTicks(4980),
                            Status = "In Progress"
                        });
                });

            modelBuilder.Entity("go_han.Models.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DivisionId = 1,
                            ProjectId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DivisionId = 2,
                            ProjectId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("go_han.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "employee"
                        });
                });

            modelBuilder.Entity("go_han.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int>("AssignerId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssignerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 3,
                            AssignerId = 1,
                            Content = "Description A",
                            Difficulty = "Easy",
                            MemberComment = "",
                            ProjectId = 1,
                            Status = 0,
                            Title = "Task A"
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 3,
                            AssignerId = 2,
                            Content = "Description B",
                            Difficulty = "Medium",
                            MemberComment = "",
                            ProjectId = 1,
                            Status = 0,
                            Title = "Task B"
                        },
                        new
                        {
                            Id = 3,
                            AssigneeId = 4,
                            AssignerId = 1,
                            Content = "Description C",
                            Difficulty = "Hard",
                            MemberComment = "",
                            ProjectId = 1,
                            Status = 1,
                            Title = "Task C"
                        });
                });

            modelBuilder.Entity("go_han.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 15, 28, 28, 23, DateTimeKind.Local).AddTicks(4900),
                            Email = "admin@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENN3GZoVTKgTDI9++cS6pBSlbQ204/mNm2GBvfOUNt9nyQEKvxILCx0mTJVoVL+sCw==",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 15, 28, 28, 23, DateTimeKind.Local).AddTicks(4930),
                            Email = "employee@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENN3GZoVTKgTDI9++cS6pBSlbQ204/mNm2GBvfOUNt9nyQEKvxILCx0mTJVoVL+sCw==",
                            RoleId = 2,
                            Username = "employee"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 15, 28, 28, 23, DateTimeKind.Local).AddTicks(4930),
                            Email = "Edi@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENN3GZoVTKgTDI9++cS6pBSlbQ204/mNm2GBvfOUNt9nyQEKvxILCx0mTJVoVL+sCw==",
                            RoleId = 2,
                            Username = "Edi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 15, 28, 28, 23, DateTimeKind.Local).AddTicks(4930),
                            Email = "Kurniadi@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENN3GZoVTKgTDI9++cS6pBSlbQ204/mNm2GBvfOUNt9nyQEKvxILCx0mTJVoVL+sCw==",
                            RoleId = 2,
                            Username = "Kurniadi"
                        });
                });

            modelBuilder.Entity("go_han.Models.Project", b =>
                {
                    b.HasOne("go_han.Models.User", "CoLead")
                        .WithMany()
                        .HasForeignKey("CoLeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("go_han.Models.User", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoLead");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("go_han.Models.ProjectMember", b =>
                {
                    b.HasOne("go_han.Models.Division", "Division")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("go_han.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("go_han.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("go_han.Models.TaskItem", b =>
                {
                    b.HasOne("go_han.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("go_han.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("go_han.Models.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("go_han.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Assignee");

                    b.Navigation("Assigner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("go_han.Models.User", b =>
                {
                    b.HasOne("go_han.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("go_han.Models.Division", b =>
                {
                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("go_han.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("go_han.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("go_han.Models.User", b =>
                {
                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
